### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by atawfiq-it** [frkyldrm/Laravel-8-Multi-Auth-with-Jetstream-Fortify-and-Livewire#1]
First of all, great work.
There's a spelling mistake in app/Http/Responses/LoginResponse.php
It should be 'dashboard' instead of 'dasboard'

**Comment by FARUK-YILDIRIM** [comment]
Thank you for warning.

> First of all, great work. There's a spelling mistake in app/Http/Responses/LoginResponse.php It should be 'dashboard' instead of 'dasboard'

Thank you very much for providing me with the information about my work. I truly appreciate your assistance and the time you took to share this with me.
